apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: demo-ms-app
  name: demo-ms-app
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: demo-ms-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: demo-ms-app
      name: demo-ms-app
    spec:
      containers:
      - args:
        - -Xmx2048m
        - -Xms2048m
        - -Xmn1024m
        - -Xss512k
        - -server
        - -XX:MaxPermSize=256m
        - -jar
        - /app.jar
        - --spring.profiles.active=dev
        command:
        - java
        - -Djava.security.egd=file:/dev/./urandom
        - -Duser.timezone=Asia/Shanghai
        image: ${ORIGIN_REPO}/${REPO}:${IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        name: demo-ms-app
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8899
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 5
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aeondockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
